-- id name category default_role time_id

-- category = ((1, '测试'), (2, '管理'))
-- default_role = ((1, "R"), (2, "S"), (3, "M"))

insert into `tb_time_content` values ('1', '车辆准备（上转鼓）', 1, 1, 1);
insert into `tb_time_content` values ('2', '车辆准备（不上转鼓）', 1, 1, 1);
-- insert into `tb_time_content` values ('3', '测试准备', '101', NULL);
-- insert into `tb_time_content` values ('4', '怠速测试', '101', NULL);
-- insert into `tb_time_content` values ('5', '轮胎噪声认可', '101', NULL);
-- insert into `tb_time_content` values ('6', '内部噪声', '101', NULL);
-- insert into `tb_time_content` values ('7', '附件整车测试准备', '101', NULL);
-- insert into `tb_time_content` values ('8', '附件噪声测试', '101', NULL);
-- insert into `tb_time_content` values ('9', '特殊测试', '101', NULL);
--
-- insert into `tb_time_content` values ('10201', '轮胎管理', '102', NULL);
-- insert into `tb_time_content` values ('10202', '准备间管理', '102', NULL);
-- insert into `tb_time_content` values ('10203', '转鼓维护', '102', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('2', '材料试验室', NULL, '3');
--
-- insert into `tb_time_content` values ('201', '测试', '2', NULL);
-- insert into `tb_time_content` values ('202', '管理', '2', NULL);
--
-- insert into `tb_time_content` values ('20101', '阻尼损耗因子试验', '201', NULL);
-- insert into `tb_time_content` values ('20102', '驻波管试验', '201', NULL);
-- insert into `tb_time_content` values ('20103', 'Alpha箱试验', '201', NULL);
-- insert into `tb_time_content` values ('20104', 'Alphamat试验', '201', NULL);
-- insert into `tb_time_content` values ('20105', '流阻试验', '201', NULL);
-- insert into `tb_time_content` values ('20106', '其他', '201', NULL);
--
-- insert into `tb_time_content` values ('20201', '测试样件准备', '202', NULL);
-- insert into `tb_time_content` values ('20202', '特供件准备', '202', NULL);
-- insert into `tb_time_content` values ('20203', '备件管理', '202', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('3', '动刚度试验室', NULL, '4');
--
-- insert into `tb_time_content` values ('301', '测试', '3', NULL);
-- insert into `tb_time_content` values ('302', '管理', '3', NULL);
--
-- insert into `tb_time_content` values ('30101', '白车身动刚度试验准备', '301', NULL);
-- insert into `tb_time_content` values ('30102', '白车身动刚度测试', '301', NULL);
-- insert into `tb_time_content` values ('30103', '舒适刚度测试', '301', NULL);
-- insert into `tb_time_content` values ('30104', '装饰车身动刚度试验准备', '301', NULL);
-- insert into `tb_time_content` values ('30105', '装饰车身动刚度测试', '301', NULL);
-- insert into `tb_time_content` values ('30106', '局部动刚度测试', '301', NULL);
-- insert into `tb_time_content` values ('30107', '仪表板认可', '301', NULL);
-- insert into `tb_time_content` values ('30108', '其他', '301', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('4', '车身隔声试验室', NULL, '5');
--
-- insert into `tb_time_content` values ('401', '测试', '4', NULL);NULL
-- insert into `tb_time_content` values ('402', '管理', '4', NULL);
--
-- insert into `tb_time_content` values ('40101', '整车隔声测试', '401', NULL);
-- insert into `tb_time_content` values ('40102', 'HVAC认可台架准备', '401', NULL);
-- insert into `tb_time_content` values ('40103', 'HVAC认可测试', '401', NULL);
-- insert into `tb_time_content` values ('40104', '附件整车测试准备', '401', NULL);
-- insert into `tb_time_content` values ('40105', '附件整车测试', '401', NULL);
-- insert into `tb_time_content` values ('40106', '冷却风扇测试台架准备', '401', NULL);
-- insert into `tb_time_content` values ('40107', '车身灵敏度测试', '401', NULL);
-- insert into `tb_time_content` values ('40108', '其他', '401', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('5', '动力总成试验室', NULL, '6');
--
-- insert into `tb_time_content` values ('501', '测试', '5', NULL);
-- insert into `tb_time_content` values ('502', '管理', '5', NULL);
--
-- insert into `tb_time_content` values ('50101', '内燃机台架准备', '501', NULL);
-- insert into `tb_time_content` values ('50102', '内燃机台架测试准备', '501', NULL);
-- insert into `tb_time_content` values ('50103', '内燃机他家测试', '501', NULL);
-- insert into `tb_time_content` values ('50104', '混合动力驱动台架准备', '501', NULL);
-- insert into `tb_time_content` values ('50105', '混合动力驱动测试准备', '501', NULL);
-- insert into `tb_time_content` values ('50106', '混合动力驱动家测试', '501', NULL);
-- insert into `tb_time_content` values ('50107', '电机台架准备', '501', NULL);
-- insert into `tb_time_content` values ('50108', '电机测试准备', '501', NULL);
-- insert into `tb_time_content` values ('50109', '电机测试', '501', NULL);
-- insert into `tb_time_content` values ('50110', '其他', '501', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('6', '前驱转鼓试验室', NULL, '7');
--
-- insert into `tb_time_content` values ('601', '测试', '6', NULL);
-- insert into `tb_time_content` values ('602', '管理', '6', NULL);
--
-- insert into `tb_time_content` values ('60101', '车辆准备（不上转鼓）', '601', NULL);
-- insert into `tb_time_content` values ('60102', '测试准备', '601', NULL);
-- insert into `tb_time_content` values ('60103', '怠速测试', '601', NULL);
-- insert into `tb_time_content` values ('60104', '附件整车测试准备', '601', NULL);
-- insert into `tb_time_content` values ('60105', '附件噪声测试', '601', NULL);
-- insert into `tb_time_content` values ('60106', '特殊测试', '601', NULL);
--
-- insert into `tb_time_content` values ('60201', '仓库管理', '602', NULL);
-- insert into `tb_time_content` values ('60202', '转鼓维护', '602', NULL);
--
--
--
--
--
-- insert into `tb_time_content` values ('7', '整车测试平台', NULL, '8');
--
-- insert into `tb_time_content` values ('701', '测试', '7', NULL);
-- insert into `tb_time_content` values ('702', '管理', '7', NULL);
--
-- insert into `tb_time_content` values ('70101', '车辆准备', '701', NULL);
-- insert into `tb_time_content` values ('70102', '测试准备（标准） ', '701', NULL);
-- insert into `tb_time_content` values ('70103', '测试准备 （特殊）', '701', NULL);
-- insert into `tb_time_content` values ('70104', '内部噪声', '701', NULL);
-- insert into `tb_time_content` values ('70105', '滚动噪声', '701', NULL);
-- insert into `tb_time_content` values ('70106', '怠速舒适性', '701', NULL);
-- insert into `tb_time_content` values ('70107', '法规噪声（老法规/C-ECAP)', '701', NULL);
-- insert into `tb_time_content` values ('70108', '其他', '701', NULL);
--
--
-- insert into `tb_time_content` values ('70201', '测试设备维护/标定', '702', NULL);
-- insert into `tb_time_content` values ('70202', '数据上传', '702', NULL);
--
-- insert into `tb_time_content` values ('70108', '其他', '701', NULL);
--
--
-- insert into `tb_time_content` values ('70201', '测试设备维护/标定', '702', NULL);
-- insert into `tb_time_content` values ('70202', '数据上传', '702', NULL);


