# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工况')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='fileinfo.Direction', verbose_name='专业方向')),
            ],
            options={
                'db_table': 'tb_direction',
                'verbose_name': '专业方向-工况',
                'verbose_name_plural': '专业方向-工况',
            },
        ),
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=25, verbose_name='平台')),
                ('carmodel', models.CharField(max_length=25, verbose_name='车型')),
                ('produce', models.CharField(max_length=25, verbose_name='生产阶段')),
                ('direction', models.CharField(max_length=25, verbose_name='专业方向')),
                ('parts', models.CharField(max_length=25, verbose_name='零部件')),
                ('status', models.CharField(max_length=128, verbose_name='工况')),
                ('author', models.CharField(max_length=25, verbose_name='试验员')),
                ('car_num', models.CharField(max_length=25, verbose_name='车号')),
                ('propulsion', models.CharField(max_length=25, verbose_name='动力总成')),
                ('power', models.CharField(max_length=25, verbose_name='功率')),
                ('create_date', models.CharField(max_length=40, verbose_name='试验时间')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=40, verbose_name='文件类型')),
                ('other_need', models.CharField(max_length=40, verbose_name='其他需求')),
            ],
            options={
                'db_table': 'tb_car',
                'verbose_name': '汽车数据信息',
                'verbose_name_plural': '汽车数据信息',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='车型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='fileinfo.Platform', verbose_name='平台')),
            ],
            options={
                'db_table': 'tb_platform',
                'verbose_name': '平台-车型',
                'verbose_name_plural': '平台-车型',
            },
        ),
        migrations.CreateModel(
            name='PropulsionPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='功率')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='fileinfo.PropulsionPower', verbose_name='动力总成')),
            ],
            options={
                'db_table': 'tb_power',
                'verbose_name': '动力总成-功率',
                'verbose_name_plural': '动力总成-功率',
            },
        ),
    ]
