# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileinfo', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_status',
            field=models.CharField(default='否', max_length=50, verbose_name='文件状态'),
        ),
    ]
