# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='其他写法')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='fileinfo.Channel', verbose_name='通道')),
            ],
            options={
                'db_table': 'tb_channel',
                'verbose_name_plural': '通道-其他写法',
                'verbose_name': '通道-其他写法',
            },
        ),
    ]
