# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileinfo', '0003_fileinfo_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='gearbox',
            field=models.CharField(default='None', max_length=40, verbose_name='变速箱信息'),
        ),
    ]
