# Generated by Django 2.2 on 2020-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='文件')),
                ('path', models.CharField(max_length=255, verbose_name='工况')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'tb_voice_file',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='voice',
            name='hdf',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='img',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='mp3',
        ),
        migrations.AddField(
            model_name='voice',
            name='file',
            field=models.ManyToManyField(db_table='tb_voice_and_file', related_name='voice_file', to='voice.FileSave', verbose_name='文件存储'),
        ),
    ]
