# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voice.Source', verbose_name='声源'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voice.Status', verbose_name='工况'),
        ),
        migrations.AlterModelTable(
            name='source',
            table='tb_voice_source',
        ),
    ]
