# Generated by Django 2.2 on 2020-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_auto_20201105_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='声源'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='工况'),
        ),
    ]
