# Generated by Django 2.2 on 2020-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_auto_20201112_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesave',
            options={'ordering': ['-id'], 'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.RemoveField(
            model_name='filesave',
            name='name',
        ),
        migrations.AlterField(
            model_name='filesave',
            name='path',
            field=models.CharField(max_length=255, verbose_name='文件'),
        ),
    ]
