# Generated by Django 2.2 on 2020-11-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voice', '0003_auto_20201109_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
    ]
