# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-08 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='试验室')),
                ('manage_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage', to=settings.AUTH_USER_MODEL, verbose_name='试验室负责人')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '试验室信息',
                'verbose_name_plural': '试验室信息',
                'db_table': 'tb_time_laboratory',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(blank=True, default=None, max_length=25, null=True, verbose_name='工时')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '试验室工时',
                'verbose_name_plural': '试验室工时',
                'db_table': 'tb_time_datetime',
            },
        ),
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='试验内容')),
                ('category', models.SmallIntegerField(choices=[(1, '测试'), (2, '管理')], default=1, verbose_name='分类')),
                ('default_role', models.SmallIntegerField(choices=[(1, 'R'), (2, 'S'), (3, 'M')], default=1, verbose_name='角色')),
                ('task_manage', models.ManyToManyField(db_table='tb_time_and_user', related_name='task_manage', to=settings.AUTH_USER_MODEL, verbose_name='信息审批人')),
                ('time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_time', to='worktime.LaboratoryTime', verbose_name='试验员工时')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_title', to='worktime.Laboratory', verbose_name='试验室名称')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '试验内容',
                'verbose_name_plural': '试验内容',
                'db_table': 'tb_time_content',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('car_number', models.CharField(max_length=50, verbose_name='车号')),
                ('vin', models.CharField(max_length=50, verbose_name='Vin码')),
                ('task_title', models.CharField(max_length=255, verbose_name='任务名称')),
                ('check_task', models.SmallIntegerField(choices=[(1, '未审核'), (2, '审核中'), (3, '已审核')], default=1, verbose_name='确认任务内容')),
                ('check_data', models.BooleanField(default=False, verbose_name='确认数据上传')),
                ('check_report', models.BooleanField(default=False, verbose_name='确认报告状况')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model', to='fileinfo.Platform', verbose_name='车型')),
                ('task_content', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_content', to='worktime.TestContent', verbose_name='任务详细内容')),
                ('task_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL, verbose_name='试验员')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '工时信息',
                'verbose_name_plural': '工时信息',
                'db_table': 'tb_time',
            },
        ),
    ]
