# Generated by Django 2.2 on 2020-12-07 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='类别')),
            ],
            options={
                'verbose_name': '错误分类',
                'verbose_name_plural': '错误分类',
                'db_table': 'tb_bug_category',
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('developer', models.SmallIntegerField(choices=[(1, '郑兴涛'), (2, '吴斌')], default=1, verbose_name='DeBug人员')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Bug信息')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已处理')], default=0, verbose_name='Bug状态')),
                ('level', models.SmallIntegerField(choices=[(0, 'Ⅰ'), (1, 'Ⅱ'), (2, 'Ⅲ'), (3, 'Ⅳ')], default=3, verbose_name='Bug级别')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.Category', verbose_name='Bug类别')),
            ],
            options={
                'verbose_name': '错误信息',
                'verbose_name_plural': '错误信息',
                'db_table': 'tb_bug',
                'ordering': ['-id'],
            },
        ),
    ]
