# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-31 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Bug信息')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已处理')], default=0, verbose_name='Bug状态')),
                ('level', models.IntegerField(choices=[(0, '一级'), (1, '二级'), (2, '三级'), (3, '四级')], default=3, verbose_name='Bug级别')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name_plural': '错误信息',
                'verbose_name': '错误信息',
                'db_table': 'tb_bug',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '错误分类',
                'verbose_name': '错误分类',
                'db_table': 'tb_bug_category',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='处理者')),
            ],
            options={
                'verbose_name_plural': '处理人员',
                'verbose_name': '处理人员',
                'db_table': 'tb_bug_developer',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.Category', verbose_name='Bug类别'),
        ),
        migrations.AddField(
            model_name='bug',
            name='developer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.Developer', verbose_name='DeBug人员'),
        ),
    ]
