# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_auto_20201026_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Ⅰ'), (1, 'Ⅱ'), (2, 'Ⅲ'), (3, 'Ⅳ')], default=3, verbose_name='Bug级别'),
        ),
    ]
