# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='download_files_data',
            field=models.IntegerField(default=0, verbose_name='数据下载'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_data',
            field=models.IntegerField(default=0, verbose_name='未完成任务'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_files_data',
            field=models.IntegerField(default=0, verbose_name='数据上传'),
        ),
    ]
