insert into `tb_audio_description` values ('1', 'Brummen');
insert into `tb_audio_description` values ('2', 'Pfeifen');
insert into `tb_audio_description` values ('3', 'Heulen');
insert into `tb_audio_description` values ('4', 'Jaulen');
insert into `tb_audio_description` values ('5', 'Schnarren');
insert into `tb_audio_description` values ('6', 'Rasseln');
insert into `tb_audio_description` values ('7', 'Heckraeusch');
insert into `tb_audio_description` values ('8', 'Rollgeraeusch');
insert into `tb_audio_description` values ('10', 'Torus');
insert into `tb_audio_description` values ('11', 'Start/stop');
insert into `tb_audio_description` values ('12', 'Motor Rauh/laut/present');
insert into `tb_audio_description` values ('13', 'Bodyboom');